### ISSUE TITLE
Use window names instead of program file names

### ISSUE THREAD

**Issue by foxcpp** [foxcpp/sutrc#7]
To improve UX of course. There is some for windows listing in agent but it needs to be tweaked because service doesn't have access to user's desktop by default.

**Comment by foxcpp** [comment]
See `nosvc` branch. We are not using services anymore and thus this task is trivial and already done in mentioned branch.

However, there is a lot of garbage in window list reported by windows, either we should filter it or revert back to using process names. Thoughts?

**Comment by Hexawolf** [comment]
For Windows, those names are common and stay same between Windows installations. I don't think there is any convenient way to differentiate between a real window and just a GUI handle, which is a pain thanks to Microsoft. Leave this issue open for now, but the only one temporary solution I have in mind is to create hand-made list of common windows that must be ignored.
